version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'no'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:8080
  redis:
    image: redis